### ISSUE TITLE
[PE-D][Tester A] Commands not explained in the User Guide

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2113-T18-2/tp#105]
`/delete` , `/find`, `/exit` does not have any elaboration on the commands
![image.png](https://raw.githubusercontent.com/CheahHaoYi/ped/main/files/8161d2f7-8221-4ff9-a6e1-fab9cfc1b9c8.png)

-------------
Labels: `severity.High` `type.DocumentationBug`
original: CheahHaoYi/ped#7

**Comment by Than-Duc-Huy** [comment]
User Guide updated
