### ISSUE TITLE
/find (Final Major Update)

### ISSUE THREAD

**Issue by Than-Duc-Huy** [AY2223S1-CS2113-T18-2/tp#147]
- The list only have 5 entries but find pickout multiple recipe because of the ingredients!
- Separate ingredients and title

![image](https://user-images.githubusercontent.com/32756835/199025676-d41949aa-39bb-40ad-b7f8-ec2e8e949986.png)

**Comment by Than-Duc-Huy** [comment]
Parse 
`/find -t <title>`
`/find -i <ingredients>`

**Comment by qianz-z** [comment]
Resolve issue in PR #164
