### ISSUE TITLE
Edit feature bugs and room for improvements

### ISSUE THREAD

**Issue by qianz-z** [AY2223S1-CS2113-T18-2/tp#149]
Listing the bugs found in edit feature. 
1. Unable to save new edits. 
![image](https://user-images.githubusercontent.com/85693125/199161561-57c7f205-ba9c-48dc-bc5b-d0215021223d.png)
This bug surfaced after the add feature was updated. Maybe it has got to do with the DuplicateRecipeTitle.
2. Syntax description is added to the recipe content.
![image](https://user-images.githubusercontent.com/85693125/199161644-80ebb007-f0ed-46b1-9314-35d16716b736.png) 
Maybe when adding the content in, you forgot to remove the flags.

**Comment by qianz-z** [comment]
3. Unable to delete title?
![image](https://user-images.githubusercontent.com/85693125/199163166-c7e2ca4d-7973-4f3d-b631-37cdd36db9da.png)

**Comment by qianz-z** [comment]
Point numbers 2 and 3 fixed.

**Comment by qianz-z** [comment]
4. Can have a better invalid command description.
![image](https://user-images.githubusercontent.com/85693125/199164433-e69e0e16-80aa-443f-94b4-1914ee945fa7.png)

**Comment by qianz-z** [comment]
5. (room for improvement) Delete function can accept index as well
![image](https://user-images.githubusercontent.com/85693125/199165732-8ea3a044-4141-4ffc-baf8-5df3b9a856f5.png)

**Comment by qianz-z** [comment]
6. More descriptive /help 
![image](https://user-images.githubusercontent.com/85693125/199165936-09f18143-d24a-4c68-bbe7-5a0b32efb535.png)

**Comment by Than-Duc-Huy** [comment]
Point 1. fixed

**Comment by qianz-z** [comment]
Points 4 and 6 done.
Left: Point 5

**Comment by qianz-z** [comment]
Point 5 fixed
