### ISSUE TITLE
Incorrect parsing of /edit command

### ISSUE THREAD

**Issue by qianz-z** [AY2223S1-CS2113-T18-2/tp#181]
Irrelevant flags should be ignored and should not be added into the recipe. This bug occurs for both ingredient and step. It will be great to solve this bug!
![image](https://user-images.githubusercontent.com/85693125/200174151-3d5a2ab7-5488-4f61-9a22-85df737d4ad3.png)![image](https://user-images.githubusercontent.com/85693125/200174143-4bd77ca0-db3c-469d-96a0-da19179f954b.png)

**Comment by snuckerzlol** [comment]
Resolved
