### ISSUE TITLE
[PE-D][Tester C] past recipes are not stored and read after exiting and opening the app

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2113-T18-2/tp#99]
![Screenshot (33).png](https://raw.githubusercontent.com/Zhai-Yuxin/ped/main/files/2ba383c4-ea4d-4383-99c4-67cf191d837b.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: Zhai-Yuxin/ped#5

**Comment by Than-Duc-Huy** [comment]
storage functionality updated
